### ISSUE TITLE
realtime_specfile in Realtime Service Runtime

### ISSUE THREAD

**Issue by jasonrogena** [onaio/ansible-druid#6]
`realtime_specfile` in the `runtime.properties` template for the realtime service doesn't get replaced when the template file is copied. Causes the service to constantly restart after deployment.

**Comment by pld** [comment]
Weird we should probably default deploy without real-time, most setups
probably do not user it (instead they use tranquility or supervisors like
we do)

**Comment by pld** [comment]
We removed realtime from our deploy to solve this
